version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
  django:
    container_name: django
    env_file:
      - .env.prod
    build: backend
    expose:
      - 8000
    depends_on:
      - postgres
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - "8000:80"
  angular:
    container_name: angular
    build: frontend
    ports:
      - "4200:80"
volumes:
  postgres-data:
    external: false