version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    container_name: backend
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
volumes:
  postgres-data:
    external: false