version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
  django:
    container_name: django
    env_file:
      - .env.docker
    environment:
      - DEBUG=False
    build: backend
    expose:
      - 8000
    depends_on:
      - postgres
    volumes:
      - media:/media
      - static:/static
  angular:
    container_name: angular
    build: frontend
    expose:
      - 4200
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - "80:80"
    volumes:
      - media:/media
      - static:/static
volumes:
  postgres-data:
  media:
  static: