# Generated by Django 4.2 on 2023-05-14 18:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hr_api.models.shared


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('experience', models.CharField(blank=True, choices=[('<1', 'Меньше 1 года'), ('1-3', 'От 1 года до 3 лет'), ('3-6', 'От 3 до 6 лет'), ('>6', 'Больше 6 лет')], max_length=3, null=True)),
                ('photo', models.ImageField(blank=True, upload_to=hr_api.models.shared.get_upload_path)),
                ('email_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PDFResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=hr_api.models.shared.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('employment', models.CharField(choices=[('PART', 'Частичная занятость'), ('FULL', 'Полная занятость')], max_length=4)),
                ('schedule', models.CharField(choices=[('DISTANT', 'Удаленная работа'), ('FLEX', 'Гибкий график'), ('SHIFT', 'Сменный график'), ('FULL', 'Полная работа')], max_length=7)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PUBLIC', 'Публично'), ('ARCHIVED', 'Архивировано'), ('DELETED', 'Удалено')], default='PUBLIC', max_length=15)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_api.department')),
                ('required_skills', models.ManyToManyField(blank=True, to='hr_api.skill')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RESUME-RESPONSE', 'Отклик на резюме'), ('VACANCY-RESPONSE', 'Отклик на вакансию')], max_length=255)),
                ('value', models.JSONField()),
                ('read', models.BooleanField(default=False)),
                ('notify_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='current_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_api.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='existing_skills',
            field=models.ManyToManyField(blank=True, to='hr_api.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('pdfresume_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hr_api.pdfresume')),
                ('desired_position', models.CharField(max_length=255)),
                ('desired_salary', models.IntegerField()),
                ('desired_employment', models.CharField(choices=[('PART', 'Частичная занятость'), ('FULL', 'Полная занятость')], max_length=4)),
                ('desired_schedule', models.CharField(choices=[('DISTANT', 'Удаленная работа'), ('FLEX', 'Гибкий график'), ('SHIFT', 'Сменный график'), ('FULL', 'Полная работа')], max_length=7)),
                ('status', models.CharField(choices=[('PUBLIC', 'Публично'), ('ARCHIVED', 'Архивировано'), ('DELETED', 'Удалено')], default='PUBLIC', max_length=15)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('hr_api.pdfresume',),
        ),
    ]
