# Generated by Django 4.1.2 on 2022-10-28 16:28

from django.db import migrations, models
import django.db.models.deletion
import hr_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='currentDepartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_api.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, choices=[('<1', 'Меньше 1 года'), ('1-3', 'От 1 года до 3 лет'), ('3-6', 'От 3 до 6 лет'), ('>6', 'Больше 6 лет')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=hr_api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='existing_skills',
            field=models.ManyToManyField(blank=True, to='hr_api.skill'),
        ),
    ]
