# Generated by Django 4.2 on 2023-06-07 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('in_work', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('employee_report', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('inWork', 'В работе'), ('onReview', 'На согласовании'), ('returned', 'Возвращена'), ('completed', 'Выполнена'), ('canceled', 'Отменена')], default='inWork', max_length=255)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_api.grade')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
