# Generated by Django 4.1.2 on 2022-10-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0002_skill_user_contact_user_currentdepartment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='currentDepartment',
            new_name='current_department',
        ),
    ]
