# Generated by Django 4.2 on 2023-06-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0002_grade_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
