# Generated by Django 4.1.2 on 2022-10-29 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hr_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0003_rename_currentdepartment_user_current_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_position', models.CharField(max_length=255)),
                ('desired_salary', models.IntegerField()),
                ('desired_employment', models.CharField(choices=[('PART', 'Частичная занятость'), ('FULL', 'Полная занятость')], max_length=4)),
                ('desired_schedule', models.CharField(choices=[('DISTANT', 'Удаленная работа'), ('FLEX', 'Гибкий график'), ('SHIFT', 'Сменный график'), ('FULL', 'Полная работа')], max_length=7)),
                ('resume', models.FileField(upload_to=hr_api.models.get_upload_path)),
                ('is_active', models.BooleanField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
