# Generated by Django 4.1.5 on 2023-03-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0008_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='is_active',
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'Публично'), ('ARCHIVED', 'Архивировано'), ('DELETED', 'Удалено')], default='PUBLIC', max_length=15),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'Публично'), ('ARCHIVED', 'Архивировано'), ('DELETED', 'Удалено')], default='PUBLIC', max_length=15),
        ),
    ]
