# Generated by Django 4.1.5 on 2023-03-21 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0009_remove_resume_is_active_remove_vacancy_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
