# Generated by Django 4.1.5 on 2023-04-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0010_alter_resume_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_api.department'),
        ),
    ]
