# Generated by Django 4.2 on 2023-05-13 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0011_alter_vacancy_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('resumeResponse', 'Отклик на резюме'), ('vacancyResponse', 'Отклик на вакансию')], max_length=255)),
                ('value', models.JSONField()),
                ('read', models.BooleanField(default=False)),
                ('notify_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
