# Generated by Django 4.2 on 2023-05-13 21:46

from django.db import migrations, models
import django.db.models.deletion
import hr_api.models.shared


class Migration(migrations.Migration):

    dependencies = [
        ('hr_api', '0013_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=hr_api.models.shared.get_upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='pdfresume_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hr_api.pdfresume'),
            preserve_default=False,
        ),
    ]
